// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarMinds.Infraestructura.AccesoDatos.EF;

#nullable disable

namespace StellarMinds.Infraestructura.Migrations
{
    [DbContext(typeof(StellarMindsContext))]
    [Migration("20260610204329_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("StockSinUSo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.ObjetoCeleste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MagnitudAparente")
                        .HasColumnType("float");

                    b.Property<string>("TipoCeleste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObjetosCeleste");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaObs")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjetoCelesteId")
                        .HasColumnType("int");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjetoCelesteId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.PrestamoDetalle", b =>
                {
                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoId", "EquipoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("PrestamoDetalles");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Camara", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<int>("Resolucion")
                        .HasColumnType("int");

                    b.Property<int>("TamañoPixel")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Montura", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<decimal>("CargaUtil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EsComputarizado")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Ocular", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<int>("AnguloVision")
                        .HasColumnType("int");

                    b.Property<int>("Diametro")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Telescopio", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<int>("Apertura")
                        .HasColumnType("int");

                    b.Property<int>("DistanciaFocal")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RelacionFocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Telescopio");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Administrador", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Coordinador", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Coordinador");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Socio", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOCantidadDisponible", "CantidadDisponible", b1 =>
                        {
                            b1.Property<int>("EquipoId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("CantidadDisponible");

                            b1.HasKey("EquipoId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOMarca", "Marca", b1 =>
                        {
                            b1.Property<int>("EquipoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Marca");

                            b1.HasKey("EquipoId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOModelo", "Modelo", b1 =>
                        {
                            b1.Property<int>("EquipoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Modelo");

                            b1.HasKey("EquipoId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoId");
                        });

                    b.Navigation("CantidadDisponible")
                        .IsRequired();

                    b.Navigation("Marca")
                        .IsRequired();

                    b.Navigation("Modelo")
                        .IsRequired();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Log", b =>
                {
                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.ObjetoCeleste", b =>
                {
                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOName", "Nombre", b1 =>
                        {
                            b1.Property<int>("ObjetoCelesteId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nombre");

                            b1.HasKey("ObjetoCelesteId");

                            b1.ToTable("ObjetosCeleste");

                            b1.WithOwner()
                                .HasForeignKey("ObjetoCelesteId");
                        });

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Observacion", b =>
                {
                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.ObjetoCeleste", "ObjetoCeleste")
                        .WithMany()
                        .HasForeignKey("ObjetoCelesteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetoCeleste");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Prestamo", b =>
                {
                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOEstado", "Estado", b1 =>
                        {
                            b1.Property<int>("PrestamoId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Estado");

                            b1.HasKey("PrestamoId");

                            b1.ToTable("Prestamos");

                            b1.WithOwner()
                                .HasForeignKey("PrestamoId");
                        });

                    b.Navigation("Estado")
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.PrestamoDetalle", b =>
                {
                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Equipo", "Equipo")
                        .WithMany("PrestamoDetalles")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Prestamo", "Prestamo")
                        .WithMany("PrestamoDetalles")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOName", "Name", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOAddress", "Adress", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<int>("Apartamento")
                                .HasColumnType("int")
                                .HasColumnName("Apartamento");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Calle");

                            b1.Property<int>("NumeroPuerta")
                                .HasColumnType("int")
                                .HasColumnName("NumeroPuerta");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOEmail", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOPassword", "Password", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Password");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOUserName", "UserName", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("UserName");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Adress")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("UserName")
                        .IsRequired();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Camara", b =>
                {
                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOTipoSensor", "TipoSensor", b1 =>
                        {
                            b1.Property<int>("CamaraId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("TipoSensor");

                            b1.HasKey("CamaraId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("CamaraId");
                        });

                    b.Navigation("TipoSensor")
                        .IsRequired();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Montura", b =>
                {
                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOTipoMontura", "TipoMontura", b1 =>
                        {
                            b1.Property<int>("MonturaId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("TipoMontura");

                            b1.HasKey("MonturaId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("MonturaId");
                        });

                    b.Navigation("TipoMontura")
                        .IsRequired();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.Navigation("PrestamoDetalles");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Prestamo", b =>
                {
                    b.Navigation("PrestamoDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
